# Generated by Django 4.1.2 on 2023-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paytmtransaction_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmtransaction',
            name='checksum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
