# Generated by Django 4.1.2 on 2023-01-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paytmtransaction_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
