# Generated by Django 4.1.5 on 2023-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paytmtransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmtransaction',
            name='status',
            field=models.CharField(choices=[('successfull', 'successfull'), ('failed', 'failed'), ('', '')], default='', max_length=20),
        ),
    ]
