# Generated by Django 4.1.2 on 2022-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='gender',
            field=models.CharField(choices=[('chemist', 'chemist'), ('user', 'user'), ('other', 'other')], default='user', max_length=10),
        ),
    ]
