# Generated by Django 4.1.2 on 2022-12-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customeuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
