# Generated by Django 4.1.2 on 2022-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customeuser_age_addressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='whatapp_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
