# Generated by Django 4.1.2 on 2022-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
