# Generated by Django 4.1.2 on 2022-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_medicine_image_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
