# Generated by Django 4.1.2 on 2022-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_ordermedicinedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='manufracturing_data',
            new_name='manufracturing_date',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='medicine',
            name='consume_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='directions_for_use',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='flavour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='precautions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='special_advice',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
