# Generated by Django 4.1.2 on 2022-12-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_manufracturing_data_medicine_manufracturing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
