# Generated by Django 4.1.2 on 2022-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_medicine_discount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='categoty',
            new_name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
