# Generated by Django 4.1.2 on 2022-12-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_order_prescription_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='userIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Delivery issue', 'Delivery issue'), ('Payment issue', 'Payment issue'), ('Quality issue', 'Quality issue'), ('Others', 'Others')], default='Delivery issue', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Delivery issue', 'Delivery issue'), ('Payment issue', 'Payment issue'), ('Quality issue', 'Quality issue'), ('Others', 'Others')], default='Initiated', max_length=30)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
