# Generated by Django 4.1.2 on 2022-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userissue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userissue',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userissue',
            name='category',
            field=models.CharField(blank=True, choices=[('Delivery issue', 'Delivery issue'), ('Payment issue', 'Payment issue'), ('Quality issue', 'Quality issue'), ('Others', 'Others')], default='Delivery issue', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userissue',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Calceled', 'Calceled')], default='Initiated', max_length=30, null=True),
        ),
    ]
