# Generated by Django 4.1.2 on 2022-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userissue_created_userissue_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userissue',
            name='issue_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
