# Generated by Django 4.1.2 on 2022-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_ordercartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
