# Generated by Django 4.1.2 on 2022-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customeuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
