# Generated by Django 4.1.2 on 2022-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_cart_is_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
