# Generated by Django 4.1.5 on 2023-01-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_order_shipping_cost_alter_order_stickers_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_friendliness', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('online_delivery', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pharmacist_knowledge', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('home_delivery', models.BooleanField(default=False)),
                ('within_quotation', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.order')),
            ],
        ),
    ]
