# Generated by Django 4.1.5 on 2023-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='online_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pharmacist_knowledge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff_friendliness',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
