# Generated by Django 4.1.2 on 2022-12-13 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='pharmacit_pics')),
                ('registration_image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='pharmacit_pics')),
                ('id_image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='pharmacit_pics')),
                ('tan_number', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
