# Generated by Django 4.1.2 on 2022-12-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userissue_issue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_price', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('meedgo_medicine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
