# Generated by Django 4.1.2 on 2022-12-13 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0002_pharmaciststock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaciststock',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmaciststock',
            name='manufracturing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
