# Generated by Django 4.1.2 on 2022-12-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userissue_issue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacist', '0003_pharmaciststock_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacistBiding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('Pharmacist_best_price', models.FloatField(default=0)),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
