# Generated by Django 4.1.2 on 2022-12-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0004_pharmacistbiding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacistbiding',
            old_name='Order',
            new_name='order',
        ),
    ]
