# Generated by Django 4.1.2 on 2022-12-14 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_userissue_issue_number'),
        ('pharmacist', '0005_rename_order_pharmacistbiding_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pharmacistbiding',
            unique_together={('user', 'order')},
        ),
    ]
