# Generated by Django 4.1.2 on 2022-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0006_alter_pharmacistbiding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistbiding',
            name='is_biding_done',
            field=models.BooleanField(default=False),
        ),
    ]
